title: CLUSIL /Information Security Association Luxembourg
email: info@clusil.lu
description: >- # this means to ignore newlines until next parameter
  Write an awesome description for your new site here.
  It will appear in your document head meta (for Google search results)

baseurl: ""
url: "http://preprod.clusil.lu"

collections:
  events:
    output: true

# Build settings
markdown: kramdown
future: True
#plugins:

deploy:
  - rsync -aze --delete ./ /var/www/clusil.lu/preprod/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
