---
new_page_extension: md
auto_deploy: true
admin_path: hibou
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - anti-money-laundering-on-blockchain
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
