---
new_page_extension: md
auto_deploy: true
admin_path: hibou
webhook_url: 
sections:
- type: jekyll-posts
  label: Events
  create: all
  templates:
  - anti-money-laundering-on-blockchain
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
