---
new_page_extension: md
auto_deploy: true
admin_path: hibou
webhook_url: 
sections:
- type: directory
  path: _events
  label: Events&Activities
  create: documents
  match: "**/*"
  templates:
  - anti-money-laundering-on-blockchain
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: yml
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
